### PR TITLE
move corr function

### PR DESCRIPTION
**Pull request by lpantano**
move correlation function of two nominal variables to R/lib

### CODE REVIEW

**Comment by kdaily** [comment]
Oops! Maybe you could put this in a better named file; I only put `dummy.R` there b/c I can't commit empty directories!

**Comment by lpantano** [comment]
yep, sorry (but was faunny). I was thinking about one file for a type of custom analysis (like correlations), but don't know. or your prefer one main file for everything?

**Comment by kdaily** [comment]
No preference! Check out this branch for what Thaneer and I have done -
there is a file in lib there for the covariate functions we're using:

https://github.com/th1vairam/pcbc_c4_analysis/tree/cov_anal

https://github.com/Sage-Bionetworks/pcbc_c4_analysis/pull/9

**Comment by kdaily** [comment]
Thanks Lorena, looks good!

**Pull request merged**
